@server = http://localhost:3000

### Listar todos os pacotes

GET {{server}}/packetRecords

### Filtrar pacotes por protocolo

GET {{server}}/packetRecords?protocol=UDP

### Buscar um pacote pelo ID existente

GET {{server}}/packetRecords/18492

### Listar todos os nós

GET {{server}}/nodeRecords

### Buscar um nó pelo ID

GET {{server}}/nodeRecords/1

### Consultar o estado da captura

GET {{server}}/capture

### Consultar as camadas de rede

GET {{server}}/layers

### Criar um pacote

# @name criarPacote
POST {{server}}/packetRecords
Content-Type: application/json

{
	"time": "23:59:59.999",
	"src": "127.0.0.1:50000",
	"dst": "127.0.0.1:443",
	"protocol": "TCP",
	"info": "Pacote criado pelo requests.http",
	"size": "64 B"
}

### Buscar o pacote criado

GET {{server}}/packetRecords/{{criarPacote.response.body.$.id}}

### Editar o pacote criado

PATCH {{server}}/packetRecords/{{criarPacote.response.body.$.id}}
Content-Type: application/json

{
	"info": "Pacote editado pelo requests.http"
}

### Excluir o pacote criado

DELETE {{server}}/packetRecords/{{criarPacote.response.body.$.id}}

### Criar um nó

# @name criarNo
POST {{server}}/nodeRecords
Content-Type: application/json

{
	"host": "node-teste",
	"ip": "127.0.0.2",
	"service": "HTTP",
	"latency": "1 ms",
	"load": "0%",
	"status": "Operacional"
}

### Buscar o nó criado

GET {{server}}/nodeRecords/{{criarNo.response.body.$.id}}

### Editar parte do nó criado

PATCH {{server}}/nodeRecords/{{criarNo.response.body.$.id}}
Content-Type: application/json

{
	"service": "HTTP / teste"
}

### Excluir o nó criado

DELETE {{server}}/nodeRecords/{{criarNo.response.body.$.id}}


